version: '3'

networks:
  db_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.19.0.0/24"
          gateway: "172.19.0.1"

services:

  # DataBase service
  database:
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ${ENV_MYSQL_DATABASE}             # DB name
      MYSQL_USER: ${ENV_MYSQL_USER}                     # USER name
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}             # USER password
      MYSQL_ROOT_PASSWORD: ${ENV_MYSQL_ROOT_PASSWORD}   # ROOT password
      # MYSQL_ROOT_HOST: ${ENV_MYSQL_ROOT_HOST}           # HOST ip address
      TZ: ${ENV_MYSQL_TIMEZONE}                         # Set DB timezone
    #volumes:
    #  - /cnt_data/mysql/mysql_conf/:/etc/mysql/conf.d/
    #  - /cnt_data/mysql/mysql_data/:/var/lib/mysql/

    networks:
      db_network:
        ipv4_address: ${ENV_MYSQL_ROOT_HOST}
    ports:
      - "${ENV_MYSQ_PORT_EXTERNAL}:${ENV_MYSQ_PORT_INTERNAL}"
    image: "mysql:5.7"

  # to check other containers in docker net
  testubuntu:
    container_name: ubuntu_db
    restart: always

    networks:
      db_network:
        ipv4_address: "172.19.0.8"
    ports:
      - "2233:22"
    image: "ubuntu:20.04"
    entrypoint: ["/bin/bash", "-c", "tail -f /dev/null"]