version: '3'

networks:
  db_network:
  web_network:
    driver: bridge

services:

  # Weather service
  weatherme:
    container_name: weather_me
    restart: always
    image: "weatherme:latest"
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${ENV_DJANGO_PORT}:${ENV_DJANGO_PORT}"

    networks:
      - db_network
      - web_network

  # Nginx service
  nginx:
    container_name: nginx_me
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - weatherme
