# Generated by Django 2.2.10 on 2021-05-09 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('fname', models.CharField(blank=True, max_length=45, null=True)),
                ('lname', models.CharField(blank=True, max_length=45, null=True)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('update_dt', models.DateTimeField(blank=True, null=True)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telegram',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'town',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeatherWb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ts', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('site', models.CharField(max_length=15)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('update_dt', models.DateTimeField(blank=True, null=True)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Town')),
            ],
            options={
                'db_table': 'weather_wb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeatherOwm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_ts', models.DateTimeField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('site', models.CharField(max_length=15)),
                ('create_dt', models.DateTimeField(blank=True, null=True)),
                ('update_dt', models.DateTimeField(blank=True, null=True)),
                ('delete_dt', models.DateTimeField(blank=True, null=True)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Town')),
            ],
            options={
                'db_table': 'weather_owm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=45)),
                ('longitude', models.CharField(max_length=45)),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Town')),
            ],
            options={
                'db_table': 'coord',
                'managed': True,
            },
        ),
    ]
