# Generated by Django 2.2.10 on 2021-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherowm',
            name='site',
            field=models.CharField(default='weatherowm', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weatherwb',
            name='site',
            field=models.CharField(default='weatherwb', max_length=15),
            preserve_default=False,
        ),
    ]
